import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import '../tokens/cookest_tokens.dart';

/// Cookest design system theme.
///
/// Provides [ThemeData] for light and dark modes using the shared
/// cross-platform design tokens generated by Style Dictionary.
///
/// Usage:
/// ```dart
/// MaterialApp(
///   theme: CookestTheme.light,
///   darkTheme: CookestTheme.dark,
/// );
/// ```
class CookestTheme {
  CookestTheme._();

  // ── Colors ──────────────────────────────────────────────

  static const Color primary = CookestTokens.colorPrimaryDEFAULT;
  static const Color primaryLight = CookestTokens.colorPrimaryLight;
  static const Color primaryDark = CookestTokens.colorPrimaryDark;
  static const Color success = CookestTokens.colorStatusSuccess;
  static const Color warning = CookestTokens.colorStatusWarning;
  static const Color error = CookestTokens.colorStatusError;
  static const Color info = CookestTokens.colorStatusInfo;

  // ── Light Theme ─────────────────────────────────────────

  static ThemeData get light => _buildTheme(
        brightness: Brightness.light,
        background: CookestTokens.colorBackgroundLight,
        surface: CookestTokens.colorSurfaceLight,
        card: CookestTokens.colorCardLight,
        heading: CookestTokens.colorHeadingLight,
        body: CookestTokens.colorTextLight,
        muted: CookestTokens.colorMutedLight,
        border: CookestTokens.colorBorderLight,
      );

  // ── Dark Theme ──────────────────────────────────────────

  static ThemeData get dark => _buildTheme(
        brightness: Brightness.dark,
        background: CookestTokens.colorBackgroundDark,
        surface: CookestTokens.colorSurfaceDark,
        card: CookestTokens.colorCardDark,
        heading: CookestTokens.colorHeadingDark,
        body: CookestTokens.colorTextDark,
        muted: CookestTokens.colorMutedDark,
        border: CookestTokens.colorBorderDark,
      );

  // ── Builder ─────────────────────────────────────────────

  static ThemeData _buildTheme({
    required Brightness brightness,
    required Color background,
    required Color surface,
    required Color card,
    required Color heading,
    required Color body,
    required Color muted,
    required Color border,
  }) {
    final colorScheme = ColorScheme(
      brightness: brightness,
      primary: primary,
      onPrimary: CookestTokens.colorWhite,
      primaryContainer: primaryLight,
      onPrimaryContainer: primaryDark,
      secondary: primaryLight,
      onSecondary: CookestTokens.colorWhite,
      secondaryContainer: primaryLight.withAlpha(77),
      onSecondaryContainer: heading,
      tertiary: info,
      onTertiary: CookestTokens.colorWhite,
      error: error,
      onError: CookestTokens.colorWhite,
      errorContainer: error.withAlpha(51),
      onErrorContainer: error,
      surface: surface,
      onSurface: heading,
      onSurfaceVariant: body,
      outline: border,
      outlineVariant: border.withAlpha(128),
      shadow: CookestTokens.colorBlack.withAlpha(26),
      scrim: CookestTokens.colorBlack.withAlpha(128),
      inverseSurface: heading,
      onInverseSurface: surface,
      inversePrimary: primaryLight,
      surfaceContainerHighest: card,
    );

    final textTheme = _buildTextTheme(heading, body, muted);

    return ThemeData(
      useMaterial3: true,
      brightness: brightness,
      colorScheme: colorScheme,
      scaffoldBackgroundColor: background,
      textTheme: textTheme,
      fontFamily: CookestTokens.fontFamilySans,
      cardTheme: CardThemeData(
        color: card,
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          side: BorderSide(color: border),
        ),
        margin: EdgeInsets.zero,
      ),
      appBarTheme: AppBarTheme(
        elevation: 0,
        scrolledUnderElevation: 0,
        backgroundColor: surface,
        foregroundColor: heading,
        titleTextStyle: GoogleFonts.playfairDisplay(
          fontSize: CookestTokens.fontSizeXl,
          fontWeight: CookestTokens.fontWeightBold,
          color: heading,
        ),
      ),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: primary,
          foregroundColor: CookestTokens.colorWhite,
          elevation: 0,
          padding: const EdgeInsets.symmetric(
            horizontal: CookestTokens.spacingN5,
            vertical: CookestTokens.spacingN2_5,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          ),
          textStyle: GoogleFonts.inter(
            fontSize: CookestTokens.fontSizeSm,
            fontWeight: CookestTokens.fontWeightSemibold,
          ),
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          foregroundColor: heading,
          side: BorderSide(color: border),
          padding: const EdgeInsets.symmetric(
            horizontal: CookestTokens.spacingN5,
            vertical: CookestTokens.spacingN2_5,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          ),
          textStyle: GoogleFonts.inter(
            fontSize: CookestTokens.fontSizeSm,
            fontWeight: CookestTokens.fontWeightSemibold,
          ),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: heading,
          padding: const EdgeInsets.symmetric(
            horizontal: CookestTokens.spacingN3,
            vertical: CookestTokens.spacingN1_5,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(CookestTokens.radiusLg),
          ),
          textStyle: GoogleFonts.inter(
            fontSize: CookestTokens.fontSizeSm,
            fontWeight: CookestTokens.fontWeightSemibold,
          ),
        ),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: false,
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          borderSide: BorderSide(color: border),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          borderSide: BorderSide(color: border),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          borderSide: const BorderSide(color: primary, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          borderSide: const BorderSide(color: error),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusXl),
          borderSide: const BorderSide(color: error, width: 2),
        ),
        contentPadding: const EdgeInsets.symmetric(
          horizontal: CookestTokens.spacingN4,
          vertical: CookestTokens.spacingN2_5,
        ),
        labelStyle: GoogleFonts.inter(
          fontSize: CookestTokens.fontSizeSm,
          fontWeight: CookestTokens.fontWeightMedium,
          color: heading,
        ),
        hintStyle: GoogleFonts.inter(
          fontSize: CookestTokens.fontSizeSm,
          color: muted,
        ),
        errorStyle: GoogleFonts.inter(
          fontSize: CookestTokens.fontSizeXs,
          color: error,
        ),
      ),
      dividerTheme: DividerThemeData(
        color: border,
        thickness: 1,
        space: 0,
      ),
      chipTheme: ChipThemeData(
        backgroundColor: card,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusFull),
          side: BorderSide(color: border),
        ),
        labelStyle: GoogleFonts.inter(
          fontSize: CookestTokens.fontSizeXs,
          fontWeight: CookestTokens.fontWeightMedium,
        ),
        padding: const EdgeInsets.symmetric(
          horizontal: CookestTokens.spacingN2_5,
          vertical: CookestTokens.spacingN1,
        ),
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: surface,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(CookestTokens.radiusN2xl),
        ),
        titleTextStyle: GoogleFonts.playfairDisplay(
          fontSize: CookestTokens.fontSizeLg,
          fontWeight: CookestTokens.fontWeightSemibold,
          color: heading,
        ),
      ),
      tooltipTheme: TooltipThemeData(
        decoration: BoxDecoration(
          color: heading,
          borderRadius: BorderRadius.circular(CookestTokens.radiusLg),
        ),
        textStyle: GoogleFonts.inter(
          fontSize: CookestTokens.fontSizeXs,
          fontWeight: CookestTokens.fontWeightMedium,
          color: surface,
        ),
      ),
      switchTheme: SwitchThemeData(
        thumbColor: WidgetStateProperty.resolveWith((states) {
          return CookestTokens.colorWhite;
        }),
        trackColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) return primary;
          return border;
        }),
      ),
    );
  }

  // ── Typography ──────────────────────────────────────────

  static TextTheme _buildTextTheme(Color heading, Color body, Color muted) {
    return TextTheme(
      displayLarge: GoogleFonts.playfairDisplay(
        fontSize: CookestTokens.fontSizeN5xl,
        fontWeight: CookestTokens.fontWeightBold,
        color: heading,
      ),
      displayMedium: GoogleFonts.playfairDisplay(
        fontSize: CookestTokens.fontSizeN4xl,
        fontWeight: CookestTokens.fontWeightBold,
        color: heading,
      ),
      displaySmall: GoogleFonts.playfairDisplay(
        fontSize: CookestTokens.fontSizeN3xl,
        fontWeight: CookestTokens.fontWeightBold,
        color: heading,
      ),
      headlineLarge: GoogleFonts.playfairDisplay(
        fontSize: CookestTokens.fontSizeN2xl,
        fontWeight: CookestTokens.fontWeightSemibold,
        color: heading,
      ),
      headlineMedium: GoogleFonts.playfairDisplay(
        fontSize: CookestTokens.fontSizeXl,
        fontWeight: CookestTokens.fontWeightSemibold,
        color: heading,
      ),
      headlineSmall: GoogleFonts.playfairDisplay(
        fontSize: CookestTokens.fontSizeLg,
        fontWeight: CookestTokens.fontWeightSemibold,
        color: heading,
      ),
      titleLarge: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeLg,
        fontWeight: CookestTokens.fontWeightSemibold,
        color: heading,
      ),
      titleMedium: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeBase,
        fontWeight: CookestTokens.fontWeightMedium,
        color: heading,
      ),
      titleSmall: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeSm,
        fontWeight: CookestTokens.fontWeightMedium,
        color: heading,
      ),
      bodyLarge: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeBase,
        fontWeight: CookestTokens.fontWeightNormal,
        color: body,
        height: 1.5,
      ),
      bodyMedium: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeSm,
        fontWeight: CookestTokens.fontWeightNormal,
        color: body,
        height: 1.5,
      ),
      bodySmall: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeXs,
        fontWeight: CookestTokens.fontWeightNormal,
        color: muted,
        height: 1.5,
      ),
      labelLarge: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeSm,
        fontWeight: CookestTokens.fontWeightSemibold,
        color: heading,
      ),
      labelMedium: GoogleFonts.inter(
        fontSize: CookestTokens.fontSizeXs,
        fontWeight: CookestTokens.fontWeightMedium,
        color: heading,
      ),
      labelSmall: GoogleFonts.inter(
        fontSize: 10,
        fontWeight: CookestTokens.fontWeightMedium,
        color: muted,
        letterSpacing: 0.5,
      ),
    );
  }
}
